### ISSUE TITLE
Windows 1909 End of Support on May 11, 2021

### ISSUE THREAD

**Issue by devopsdina** [openshift/windows-machine-config-operator#451]
Are there plans to support other MachineSet images for Windows?  

Windows 1909 has gone [end of support](https://docs.microsoft.com/en-us/lifecycle/end-of-support/end-of-support-2021) as of May 11, 2021.

**Comment by aravindhp** [comment]
Which platforms are you asking for? We do support 1809 LTSC on AWS and Azure.

**Comment by devopsdina** [comment]
Hi @aravindhp!

I working in AWS, I would like to use a public AMI.  When trying to use ami `ami-015451c8bbe8e7650` which is 1809, but I am not sure if it is LTSC?

Here is more information about what I am doing, let me know if I can provide any other information.

SSHed into the Windows Machine (worker) created from the MachineSet deployment, I can verify this:
![image](https://user-images.githubusercontent.com/41236025/118305931-a928c100-b4b6-11eb-9578-5432cf52f659.png)

I get the following error in the MachineSet Machine event:
![image](https://user-images.githubusercontent.com/41236025/118308968-9d3efe00-b4ba-11eb-9993-31a3b357ec59.png)


Code used for machineset deployment:
```
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: my-ocp-instance
  name: my-ocp-instance-windows-worker-us-east-1a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: my-ocp-instance
      machine.openshift.io/cluster-api-machineset: my-ocp-instance-windows-worker-us-east-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: my-ocp-instance
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: my-ocp-instance-windows-worker-us-east-1a
        machine.openshift.io/os-id: Windows
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          ami:
             id: ami-015451c8bbe8e7650 # Windows_Server-2019-English-Full-ContainersLatest-2021.04.14
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: my-ocp-instance-worker-profile 
          instanceType: m5a.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-1a
            region: us-east-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - my-ocp-instance-worker-sg
          subnet:
            filters:
              - name: tag:Name
                values:
                  - my-ocp-instance-private-us-east-1a
          tags:
            - name: kubernetes.io/cluster/my-ocp-instance
              value: owned
          userDataSecret:
            name: windows-user-data
            namespace: openshift-machine-api
```

After pre-pulling my container image on the windows machine (required until the timeout increase is available in the operator), I get the following error while trying to deploy a container:
![image](https://user-images.githubusercontent.com/41236025/118308467-f8242580-b4b9-11eb-89d5-8a58a1886847.png)

code used for container deployment:
```apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-demo
  name: win-demo
  namespace: windows-workloads
spec:
  selector:
    matchLabels:
      app: win-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: win-demo
      name: win-demo
    spec:
      containers:
      - name: win-demo
        image: mcr.microsoft.com/windows/servercore:1809
        imagePullPolicy: IfNotPresent
        command:
        - powershell.exe
        - -command
        - $listener = New-Object System.Net.HttpListener; $listener.Prefixes.Add('http://*:80/'); $listener.Start();Write-Host('Listening at http://*:80/'); while ($listener.IsListening) { $context = $listener.GetContext(); $response = $context.Response; $content='<html><body><H1>OpenShift for Windows Containers</H1></body></html>'; $buffer = [System.Text.Encoding]::UTF8.GetBytes($content); $response.ContentLength64 = $buffer.Length; $response.OutputStream.Write($buffer, 0, $buffer.Length); $response.Close(); };
        securityContext:
          windowsOptions:
            runAsUserName: "ContainerAdministrator"
      nodeSelector:
        kubernetes.io/os-id: Windows
      tolerations:
        - key: "os"
          operator: "Equal"
          value: "Windows"
          effect: "NoSchedule"
```
