### ISSUE TITLE
Service and Endpoints for the node exporters are not correctly configured

### ISSUE THREAD

**Issue by SSvilen** [openshift/windows-machine-config-operator#826]
The windows node exporter is installed on all windows worker nodes, but the required Service and Endpoint resources are no created at all. 
There is a service object created, but it's from type ClusterIP, which in this case won't work.
The Service should be of type 'ExternalName'  and the Endpoints should be updated by the operator on every node join/deletion operation.
For instance:
 ```yml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: windows-exporter
  name: windows-exporter
  namespace: openshift-windows-machine-config-operator
spec:
  type: ExternalName
  ports:
    - name: metrics
      port: 9182
      protocol: TCP
      targetPort: 9182
  externalName: nodexporter
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    name: windows-exporter
  name: windows-exporter
  namespace: openshift-windows-machine-config-operator
subsets:
  - addresses:
      - ip: 1.1.1.1
        targetRef:
          kind: Node
          name: winmach-q84jj
          uid: ab8028e7-a0ed-4f83-89e5-b577be2231ed
      - ip: 1.1.1.1
        targetRef:
          kind: Node
          name: winmach-t5vgm
          uid: 1b710328-88d5-4142-a78f-dd414705cc19
    ports:
      - name: metrics
        port: 9182
        protocol: TCP

```

**Comment by mansikulkarni96** [comment]
@SSvilen thanks for the provided information.

As you can see in the [manifests/windows-exporter_v1_service.yaml](https://github.com/openshift/windows-machine-config-operator/blob/master/bundle/manifests/windows-exporter_v1_service.yaml), the type is not set to ClusterIP.
The required service and endpoint names should be both `windows-exporter` as that name is used to get the resources in the operator code.
I suspect monitoring is not enabled in the operator namespace. Please ensure label `openshift.io/cluster-monitoring=true` is present in the `openshift-windows-machine-config-operator` namespace which is required for  monitoring resources to be created by WMCO in that namespace.
If it is not enabled you can see a log like: `install the prometheus-operator to enable Prometheus configuration` in the WMCO logs.
Community Operators have a checkbox to enable monitoring in the operator namespace, if you are building from source you can use `oc label ns openshift-windows-machine-config-operator openshift.io/cluster-monitoring=true --overwrite` to set the label.
Let us know if that resolves the issue!

**Comment by SSvilen** [comment]
@mansikulkarni96,

The monitoring for the namespace is enabled. The problem is that the node exporter is installed on the windows worker nodes and it's not running as a pod, like it is for the linux based os. So prometheus operator can not properly discover the endpoint for that servicemonitor. 
So I had to recreate the service and manually create the endpoint object, which in turn points to the windows nodes. 
Or am I overthinking this?

**Comment by mansikulkarni96** [comment]
@SSvilen Thanks for confirming that.
The behaviour you see is the expected behaviour, windows-exporter runs as a Windows service on the Windows nodes which is different from it's linux counterpart due to support reasons.
Prometheus operator should be able to discover the endpoint, you can take a look at the [service_monitor.yaml](https://github.com/openshift/windows-machine-config-operator/blob/cb5f6707181521a75cf06da208b962b448fda322/bundle/manifests/windows-exporter_monitoring.coreos.com_v1_servicemonitor.yaml#L13), you can see how the re-labellings are applied to make the endpoint discoverable.
What you are expecting is exactly what the operator does, it updates the endpoint objects on every node join/deletion operation, more details in [metrics.go](https://github.com/openshift/windows-machine-config-operator/blob/cb5f6707181521a75cf06da208b962b448fda322/pkg/metrics/metrics.go#L132) if you are interested in the code base.
If you could provide Windows Machine Config Operator logs and details about the exact operator version, OCP version and the steps followed to reach this point, I should be able to help you out further.

**Comment by SSvilen** [comment]
OK, I see what's happening. 
```
controller.windowsmachine    invalid Machine    {"name": "winmach-t5vgm", "error": "no internal IP address associated",
```
and based on the code in [metrics.go ](https://github.com/openshift/windows-machine-config-operator/blob/cb5f6707181521a75cf06da208b962b448fda322/pkg/metrics/metrics.go#L132) an internal IP address is expected.

The status field of the machine shows type 'InternalDNS'

```yml
status:                                                                                                                                                                                                                                    
  addresses:                                                                                                                                                                                                                               
   - address: winmach-q84jj                                                                                                                                                                                                                 
     type: InternalDNS
```

I'm not sure why that is.
