### ISSUE TITLE
Pods metrics endpoint

### ISSUE THREAD

**Issue by SSvilen** [openshift/windows-machine-config-operator#829]
By default the pod metrics are getting scraped from the following kubelet endpoint:
/metrics/cadvisor

Which is more or less empty on windows machines.
I could workaroung that problem by creating new Service Monitor, which scrapes the mertics from the '/metrics/resource' [endpoint](https://github.com/kubernetes/kubernetes/pull/86282)

```yml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: kubelet-windows
    k8s-app: kubelet-windows
  name: kubelet-windows
  namespace: openshift-monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      bearerTokenSecret:
        key: ""
      honorLabels: true
      honorTimestamps: false
      interval: 30s
      path: /metrics/resource
      port: https-metrics
      relabelings:
        - sourceLabels:
            - __metrics_path__
          replacement: "/metrics/cadvisor"
          targetLabel: metrics_path
        - replacement: dummy
          targetLabel: image
      scheme: https
      scrapeTimeout: 30s
      tlsConfig:
        ca: {}
        caFile: /etc/prometheus/configmaps/kubelet-serving-ca-bundle/ca-bundle.crt
        cert: {}
  jobLabel: job
  targetLabels:
    - job
    - metrics_path
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet-windows
```

Now the CPU and memory consumption are visible in OpenShift Console. 
Or is there another (built-in) way to achive that?
